export const Defaults = {
  DEFAULT_Z_INDEX: 1000,
  DEFAULT_LINE_WIDTH: 0.15,
  INITIAL_ZOOM: 20,
  DEFAULT_FONT_FAMILY: 'Arial',
  DEFAULT_FONT_SIZE: 64,
  DEFAULT_FONT_WEIGHT: '600',
  DEFAULT_LABEL_COLOR: 0x454545,
  DEFAULT_LABEL_ALIGN: 'center',
  INITIAL_HASH: 1.0,
  DEFAULT_MIN_HASH: 0.0,
  DEFAULT_BASE_SCALE: 0.1,
} as const;
